# Generated by Django 5.1.7 on 2025-03-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modular_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='name_display',
            new_name='verbose_name',
        ),
    ]
